CREATE TABLE sip_rate_beverages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bev_type TEXT NOT NULL,
    bev_name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    overall_rating INTEGER
);

