DROP TABLE IF EXISTS sip_rate_beverages, sip_rate_users, sip_rate_reviews;


CREATE TABLE sip_rate_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now(),
    date_modified TIMESTAMP 
);

CREATE TABLE sip_rate_beverages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bev_type TEXT NOT NULL,
    bev_name TEXT NOT NULL,
    description TEXT NOT NULL,
    overall_rating TEXT,
    bev_code TEXT NOT NULL UNIQUE
);

CREATE TABLE sip_rate_reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bev_type TEXT NOT NULL,
    bev_name TEXT NOT NULL,
    user_review TEXT NOT NULL,
    rating INTEGER,
    date_created TIMESTAMP NOT NULL DEFAULT now(),
    bev_id INTEGER
        REFERENCES sip_rate_beverages(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES sip_rate_users(id) ON DELETE CASCADE NOT NULL
);


